name: Node test
run-name: Test nodejs app
on: [push]

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4
      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Instalar dependencias
        run: |
          cd calculadora
          npm install
      - name: Ejecutar Tests
        run: |
          cd calculadora
          npm run test
